### ISSUE TITLE
No effect on iOS 12

### ISSUE THREAD

**Issue by furiosFast** [Gradients/Gradients#14]
Hello, 
your library seems no longer works on iOS 12. 
Can you verify?

**Comment by muhasturk** [comment]
It is working on iOS 12 real and virtual device. Double check layer's index that is you are attempting to insert as sublayer.

**Comment by johndunne** [comment]
Confirmed. No longer working on code that was ok pre iOS 12. However, explicitly setting the frame on the CALayer fixes the issue. eg.
```
var orange_juice_layer = Gradients.orangeJuice.layer
orange_juice_layer.frame = glassView.bounds
glassView.layer.insertSublayer(orange_juice_layer, at:0)
```

**Comment by cruisediary** [comment]
@johndunne you are right it should set the frame explicitly 👍
